default_language_version.python = "3.12"

[[repos]]
repo = "git@github.com:pre-commit/pre-commit-hooks.git"
rev = "v6.0.0"
hooks = [
    {id = "check-merge-conflict"},
    {id = "check-toml"},
    {id = "check-xml"},
    {id = "check-yaml"},
    {id = "debug-statements"},
    {id = "detect-private-key"},
    {id = "end-of-file-fixer"},
    #{id = "no-commit-to-branch"},
    {id = "trailing-whitespace"},
]

[[repos]]
repo = "https://github.com/psf/black"
rev = "24.10.0"
hooks = [
    {id = "black", args = ["--config", "./pyproject.toml"]}
]

[[repos]]
repo = "https://github.com/PyCQA/isort"
rev = "5.13.2"
hooks = [
    {id = "isort", args = ["--settings-file", "./pyproject.toml"]}
]

[[repos]]
repo = "git@github.com:PyCQA/docformatter.git"
rev = "v1.7.7"
hooks = [
    {id = "docformatter", args = ["--in-place", "--config", "./pyproject.toml"]}
]

[[repos]]
repo = "git@github.com:astral-sh/ruff-pre-commit.git"
rev = "v0.15.10"
hooks = [
    {id = "ruff-check", args = ["--preview", "--fix"]},
]

[[repos]]
repo = "local"
hooks =[
    {id = "pylint", name = "pylint", entry = "pylint", language = "python", files = "\\.py$", args = ["--rcfile=./pyproject.toml"]},
    {id = "wily", name = "wily", entry = "wily diff", language = "python", files = "\\.py$", args = ["--no-detail"]}
]

[[repos]]
repo = "https://github.com/myint/eradicate"
rev = "2.3.0"
hooks = [
    {id = "eradicate", args = []}
]

[[repos]]
repo = "https://github.com/rstcheck/rstcheck"
rev = "v6.2.5"
hooks = [
    {id = "rstcheck", additional_dependencies = ["tomli", "sphinx"], args = ["-r", "--config", "./pyproject.toml"]}
]
