# Standard Library Imports
import sys

try:
    # Third Party Imports
    import gi

    gi.require_version("Gdk", "3.0")
    gi.require_version("GLib", "2.0")
    gi.require_version("Gtk", "3.0")
except ImportError:
    print("Failed to import package gi; exiting.")
    sys.exit(1)
# Third Party Imports
from gi.repository import Gdk, Gtk

EXPECTED_APPLICATIONWINDOW_METHODS = [
    "get_help_overlay",
    "get_id",
    "get_show_menubar",
    "set_help_overlay",
    "set_show_menubar",
]
EXPECTED_APPLICATIONWINDOW_PROPERTIES = {"show_menubar": True}

EXPECTED_ASSISTANT_HANDLER_IDS = {
    "apply": -1,
    "cancel": -1,
    "close": -1,
    "escape": -1,
    "prepare": -1,
}
EXPECTED_ASSISTANT_METHODS = [
    "add_action_widget",
    "append_page",
    "commit",
    "get_current_page",
    "get_n_pages",
    "get_nth_page",
    "get_page_complete",
    "get_page_has_padding",
    "get_page_title",
    "get_page_type",
    "insert_page",
    "next_page",
    "prepend_page",
    "previous_page",
    "remove_action_widget",
    "remove_page",
    "set_current_page",
    "set_forward_page_func",
    "set_page_complete",
    "set_page_has_padding",
    "set_page_title",
    "set_page_type",
    "update_buttons_state",
]
EXPECTED_ASSISTANT_PROPERTIES = {"use_header_bar": -1}

EXPECTED_SCROLLEDWINDOW_HANDLER_IDS = {
    "edge-overshot": -1,
    "edge-reached": -1,
    "move-focus-out": -1,
    "scroll-child": -1,
}
EXPECTED_SCROLLEDWINDOW_METHODS = [
    "get_capture_button_press",
    "get_hadjustment",
    "get_hscrollbar",
    "get_kinetic_scrolling",
    "get_max_content_height",
    "get_max_content_width",
    "get_min_content_height",
    "get_min_content_width",
    "get_overlay_scrolling",
    "get_placement",
    "get_policy",
    "get_propagate_natural_height",
    "get_propagate_natural_width",
    "get_shadow_type",
    "get_vadjustment",
    "get_vscrollbar",
    "set_capture_button_press",
    "set_hadjustment",
    "set_kinetic_scrolling",
    "set_max_content_height",
    "set_max_content_width",
    "set_min_content_height",
    "set_min_content_width",
    "set_overlay_scrolling",
    "set_placement",
    "set_policy",
    "set_propagate_natural_height",
    "set_propagate_natural_width",
    "set_shadow_type",
    "set_vadjustment",
    "unset_placement",
]
EXPECTED_SCROLLEDWINDOW_PROPERTIES = {
    "hadjustment": None,
    "hscrollbar_policy": Gtk.PolicyType.AUTOMATIC,
    "kinetic_scrolling": True,
    "max_content_height": -1,
    "max_content_width": -1,
    "min_content_height": -1,
    "min_content_width": -1,
    "overlay_scrolling": True,
    "propagate_natural_height": False,
    "propagate_natural_width": False,
    "shadow_type": Gtk.ShadowType.NONE,
    "vadjustment": None,
    "vscrollbar_policy": Gtk.PolicyType.AUTOMATIC,
    "window_placement": Gtk.CornerType.TOP_LEFT,
}

EXPECTED_WINDOW_HANDLER_IDS = {
    "activate-default": -1,
    "activate-focus": -1,
    "enable-debugging": -1,
    "keys-changed": -1,
    "set-focus": -1,
}
EXPECTED_WINDOW_METHODS = [
    "activate_default",
    "activate_focus",
    "activate_key",
    "add_accel_group",
    "add_mnemonic",
    "begin_move_drag",
    "begin_resize_drag",
    "close",
    "deiconify",
    "fullscreen",
    "fullscreen_on_monitor",
    "get_accept_focus",
    "get_application",
    "get_attached_to",
    "get_decorated",
    "get_default_size",
    "get_default_widget",
    "get_deletable",
    "get_destroy_with_parent",
    "get_focus",
    "get_focus_on_map",
    "get_focus_visible",
    "get_gravity",
    "get_group",
    "get_hide_titlebar_when_maximized",
    "get_icon",
    "get_icon_list",
    "get_icon_name",
    "get_mnemonic_modifier",
    "get_mnemonics_visible",
    "get_modal",
    "get_position",
    "get_resizable",
    "get_role",
    "get_screen",
    "get_size",
    "get_skip_pager_hint",
    "get_skip_taskbar_hint",
    "get_title",
    "get_titlebar",
    "get_transient_for",
    "get_type_hint",
    "get_urgency_hint",
    "get_window_type",
    "has_group",
    "has_toplevel_focus",
    "iconify",
    "is_active",
    "is_maximized",
    "maximize",
    "mnemonic_activate",
    "move",
    "present",
    "present_with_time",
    "propagate_key_event",
    "remove_accel_group",
    "remove_mnemonic",
    "resize",
    "set_accept_focus",
    "set_application",
    "set_attached_to",
    "set_decorated",
    "set_default",
    "set_default_size",
    "set_deletable",
    "set_destroy_with_parent",
    "set_focus",
    "set_focus_on_map",
    "set_focus_visible",
    "set_geometry_hints",
    "set_gravity",
    "set_has_user_ref_count",
    "set_hide_titlebar_when_maximized",
    "set_icon",
    "set_icon_from_file",
    "set_icon_list",
    "set_icon_name",
    "set_keep_above",
    "set_keep_below",
    "set_mnemonic_modifier",
    "set_mnemonics_visible",
    "set_modal",
    "set_position",
    "set_resizable",
    "set_role",
    "set_screen",
    "set_skip_pager_hint",
    "set_skip_taskbar_hint",
    "set_startup_id",
    "set_title",
    "set_titlebar",
    "set_transient_for",
    "set_type_hint",
    "set_urgency_hint",
    "stick",
    "unfullscreen",
    "unmaximize",
    "unstick",
]
EXPECTED_WINDOW_PROPERTIES = {
    "accept_focus": True,
    "application": None,
    "attached_to": None,
    "decorated": True,
    "default_height": -1,
    "default_width": -1,
    "deletable": True,
    "destroy_with_parent": False,
    "focus_on_map": True,
    "focus_visible": True,
    "gravity": Gdk.Gravity.NORTH_WEST,
    "has_toplevel_focus": False,
    "hide_titlebar_when_maximized": False,
    "icon": None,
    "icon_name": None,
    "mnemonics_visible": True,
    "modal": False,
    "resizable": True,
    "role": None,
    "screen": None,
    "skip_taskbar_hint": False,
    "startup_id": None,
    "title": "pytkwrap GTK3 window",
    "transient_for": None,
    "type": Gtk.WindowType.TOPLEVEL,
    "type_hint": Gdk.WindowTypeHint.NORMAL,
    "urgency_hint": False,
    "window_position": Gtk.WindowPosition.NONE,
}
