# Standard Library Imports
import sys

try:
    # Third Party Imports
    import gi

    gi.require_version("Gdk", "3.0")
    gi.require_version("GLib", "2.0")
    gi.require_version("Gtk", "3.0")
except ImportError:
    print("Failed to import package gi; exiting.")
    sys.exit(1)
# Third Party Imports
from gi.repository import Gdk, Gtk

EXPECTED_ADJUSTMENT_ATTRIBUTES = {"default_value": 0.0, "edit_signal": "value-changed"}
EXPECTED_ADJUSTMENT_HANDLER_IDS = {"changed": -1, "value-changed": -1}
EXPECTED_ADJUSTMENT_METHODS = [
    "clamp_page",
    "configure",
    "get_lower",
    "get_minimum_increment",
    "get_page_increment",
    "get_page_size",
    "get_step_increment",
    "get_upper",
    "get_value",
    "set_lower",
    "set_page_increment",
    "set_page_size",
    "set_step_increment",
    "set_upper",
    "set_value",
]
EXPECTED_ADJUSTMENT_PROPERTIES = {
    "lower": 0.0,
    "page_increment": 0.0,
    "page_size": 0.0,
    "step_increment": 0.0,
    "upper": 0.0,
    "value": 0.0,
}

EXPECTED_GLAREA_HANDLER_IDS = {"create-context": -1, "render": -1, "resize": -1}
EXPECTED_GLAREA_METHODS = [
    "attach_buffers",
    "get_auto_render",
    "get_context",
    "get_error",
    "get_has_alpha",
    "get_has_depth_buffer",
    "get_has_stencil_buffer",
    "get_required_version",
    "get_use_es",
    "make_current",
    "queue_render",
    "set_auto_render",
    "set_error",
    "set_has_alpha",
    "set_has_depth_buffer",
    "set_has_stencil_buffer",
    "set_required_version",
    "set_use_es",
]
EXPECTED_GLAREA_PROPERTIES = {
    "auto_render": True,
    "has_alpha": False,
    "has_depth_buffer": False,
    "has_stencil_buffer": False,
    "use_es": False,
}

EXPECTED_GOBJECT_ATTRIBUTES: dict[str, int | str | None] = {
    "axis": None,
    "canvas": None,
    "column_types": None,
    "data_type": None,
    "default_value": None,
    "edit_signal": None,
    "figure": None,
    "font_description": None,
    "format": None,
    "index": -1,
    "listen_topic": "listen-topic",
    "n_columns": None,
    "n_rows": None,
    "send_topic": "send-topic",
    "x_pos": None,
    "y_pos": None,
}
EXPECTED_GOBJECT_HANDLER_IDS = {"notify": -1}
EXPECTED_GOBJECT_METHODS = [
    "bind_property",
    "bind_property_full",
    "connect",
    "connect_after",
    "disconnect",
    "emit",
    "force_floating",
    "freeze_notify",
    "get_data",
    "get_property",
    "get_qdata",
    "getv",
    "handler_block",
    "handler_unblock",
    "is_floating",
    "notify",
    "notify_by_pspec",
    "ref",
    "ref_sink",
    "run_dispose",
    "set_data",
    "set_property",
    "steal_data",
    "steal_qdata",
    "thaw_notify",
    "unref",
    "watch_closure",
]

EXPECTED_IMAGE_METHODS = [
    "clear",
    "get_alignment",
    "get_animation",
    "get_gicon",
    "get_icon_name",
    "get_icon_set",
    "get_padding",
    "get_pixbuf",
    "get_pixel_size",
    "get_storage_type",
    "set_alignment",
    "set_from_animation",
    "set_from_file",
    "set_from_gicon",
    "set_from_icon_name",
    "set_from_icon_set",
    "set_from_pixbuf",
    "set_from_resource",
    "set_from_surface",
    "set_pixel_size",
    "set_padding",
]
EXPECTED_IMAGE_PROPERTIES = {
    "file": None,
    "gicon": None,
    "icon_name": None,
    "icon_size": 4,
    "pixbuf": None,
    "pixbuf_animation": None,
    "pixel_size": -1,
    "resource": None,
    "surface": None,
    "use_fallback": False,
}

EXPECTED_POPOVER_HANDLER_IDS = {"closed": -1}
EXPECTED_POPOVER_METHODS = [
    "bind_model",
    "get_constrain_to",
    "get_default_widget",
    "get_modal",
    "get_pointing_to",
    "get_position",
    "get_relative_to",
    "popdown",
    "popup",
    "set_constrain_to",
    "set_default_widget",
    "set_modal",
    "set_pointing_to",
    "set_position",
    "set_relative_to",
]
EXPECTED_POPOVER_PROPERTIES = {
    "constrain_to": Gtk.PopoverConstraint.WINDOW,
    "modal": True,
    "pointing_to": None,
    "position": Gtk.PositionType.TOP,
    "relative_to": None,
}

EXPECTED_RANGE_ATTRIBUTES = {"edit_signal": "value-changed"}
EXPECTED_RANGE_HANDLER_IDS = {
    "adjust-bounds": -1,
    "change-value": -1,
    "move-slider": -1,
    "value-changed": -1,
}
EXPECTED_RANGE_METHODS = [
    "get_adjustment",
    "get_fill_level",
    "get_flippable",
    "get_inverted",
    "get_lower_stepper_sensitivity",
    "get_range_rect",
    "get_restrict_to_fill_level",
    "get_round_digits",
    "get_show_fill_level",
    "get_slider_range",
    "get_slider_size_fixed",
    "get_upper_stepper_sensitivity",
    "get_value",
    "set_adjustment",
    "set_fill_level",
    "set_flippable",
    "set_increments",
    "set_inverted",
    "set_lower_stepper_sensitivity",
    "set_range",
    "set_restrict_to_fill_level",
    "set_round_digits",
    "set_show_fill_level",
    "set_slider_size_fixed",
    "set_upper_stepper_sensitivity",
    "set_value",
]
EXPECTED_RANGE_PROPERTIES = {
    "adjustment": None,
    "fill_level": 1.7976931348623157e308,
    "inverted": False,
    "restrict_to_fill_level": True,
    "round_digits": -1,
    "show_fill_level": False,
}

EXPECTED_SCALE_HANDLER_IDS = {"format-value": -1}
EXPECTED_SCALE_METHODS = [
    "add_mark",
    "clear_marks",
    "get_digits",
    "get_draw_value",
    "get_has_origin",
    "get_layout",
    "get_layout_offsets",
    "get_value_pos",
    "set_digits",
    "set_draw_value",
    "set_has_origin",
    "set_value_pos",
]
EXPECTED_SCALE_PROPERTIES = {
    "digits": 1,
    "draw_value": True,
    "has_origin": True,
    "value_pos": Gtk.PositionType.TOP,
}

EXPECTED_WIDGET_ATTRIBUTES: dict[str, int | str | None] = {
    "axis": None,
    "canvas": None,
    "column_types": None,
    "data_type": None,
    "default_value": None,
    "edit_signal": None,
    "figure": None,
    "font_description": None,
    "format": None,
    "n_columns": None,
    "n_rows": None,
    "x_pos": 0,
    "y_pos": 0,
}
EXPECTED_WIDGET_HANDLER_IDS = {
    "destroy": -1,
    "direction-changed": -1,
    "hide": -1,
    "keynav-failed": -1,
    "map": -1,
    "mnemonic-activate": -1,
    "move-focus": -1,
    "query-tooltip": -1,
    "realize": -1,
    "show": -1,
    "state-flags-changed": -1,
    "unmap": -1,
    "unrealize": -1,
}
EXPECTED_WIDGET_METHODS = [
    "activate",
    "add_accelerator",
    "add_device_events",
    "add_events",
    "add_mnemonic_label",
    "add_tick_callback",
    "can_activate_accel",
    "child_focus",
    "child_notify",
    "compute_expand",
    "create_pango_context",
    "create_pango_layout",
    "destroy",
    "destroyed",
    "device_is_shadowed",
    "drag_begin_with_coordinates",
    "drag_check_threshold",
    "drag_dest_add_image_targets",
    "drag_dest_add_text_targets",
    "drag_dest_add_uri_targets",
    "drag_dest_find_target",
    "drag_dest_get_target_list",
    "drag_dest_get_track_motion",
    "drag_dest_set",
    "drag_dest_set_target_list",
    "drag_dest_set_track_motion",
    "drag_dest_unset",
    "drag_get_data",
    "drag_highlight",
    "drag_source_add_image_targets",
    "drag_source_add_text_targets",
    "drag_source_add_uri_targets",
    "drag_source_get_target_list",
    "drag_source_set",
    "drag_source_set_icon_gicon",
    "drag_source_set_icon_name",
    "drag_source_set_icon_pixbuf",
    "drag_source_set_target_list",
    "drag_source_unset",
    "drag_unhighlight",
    "draw",
    "error_bell",
    "event",
    "freeze_child_notify",
    "get_accessible",
    "get_action_group",
    "get_allocated_baseline",
    "get_allocated_height",
    "get_allocated_size",
    "get_allocated_width",
    "get_allocation",
    "get_ancestor",
    "get_app_paintable",
    "get_can_default",
    "get_can_focus",
    "get_child_visible",
    "get_clip",
    "get_clipboard",
    "get_device_enabled",
    "get_device_events",
    "get_direction",
    "get_display",
    "get_double_buffered",
    "get_events",
    "get_focus_on_click",
    "get_font_map",
    "get_font_options",
    "get_frame_clock",
    "get_halign",
    "get_has_tooltip",
    "get_has_window",
    "get_hexpand",
    "get_hexpand_set",
    "get_mapped",
    "get_margin_bottom",
    "get_margin_end",
    "get_margin_start",
    "get_margin_top",
    "get_modifier_mask",
    "get_name",
    "get_no_show_all",
    "get_opacity",
    "get_pango_context",
    "get_parent",
    "get_parent_window",
    "get_path",
    "get_preferred_height",
    "get_preferred_height_and_baseline_for_width",
    "get_preferred_height_for_width",
    "get_preferred_size",
    "get_preferred_width",
    "get_preferred_width_for_height",
    "get_realized",
    "get_receives_default",
    "get_request_mode",
    "get_scale_factor",
    "get_screen",
    "get_sensitive",
    "get_settings",
    "get_size_request",
    "get_state_flags",
    "get_style_context",
    "get_support_multidevice",
    "get_template_child",
    "get_tooltip_markup",
    "get_tooltip_text",
    "get_tooltip_window",
    "get_toplevel",
    "get_valign",
    "get_valign_with_baseline",
    "get_vexpand",
    "get_vexpand_set",
    "get_visible",
    "get_visual",
    "get_window",
    "grab_add",
    "grab_default",
    "grab_focus",
    "grab_remove",
    "has_default",
    "has_focus",
    "has_grab",
    "has_visible_focus",
    "hide",
    "hide_on_delete",
    "in_destruction",
    "init_template",
    "input_shape_combine_region",
    "insert_action_group",
    "intersect",
    "is_ancestor",
    "is_drawable",
    "is_focus",
    "is_sensitive",
    "is_toplevel",
    "is_visible",
    "keynav_failed",
    "list_accel_closures",
    "list_action_prefixes",
    "list_mnemonic_labels",
    "map",
    "mnemonic_activate",
    "queue_allocate",
    "queue_draw",
    "queue_draw_area",
    "queue_resize",
    "queue_resize_no_redraw",
    "realize",
    "register_window",
    "remove_accelerator",
    "remove_mnemonic_label",
    "remove_tick_callback",
    "reset_style",
    "send_focus_change",
    "set_accel_path",
    "set_allocation",
    "set_app_paintable",
    "set_can_default",
    "set_can_focus",
    "set_child_visible",
    "set_clip",
    "set_device_enabled",
    "set_device_events",
    "set_direction",
    "set_events",
    "set_focus_on_click",
    "set_font_map",
    "set_font_options",
    "set_halign",
    "set_has_tooltip",
    "set_has_window",
    "set_hexpand",
    "set_hexpand_set",
    "set_mapped",
    "set_margin_bottom",
    "set_margin_end",
    "set_margin_start",
    "set_margin_top",
    "set_name",
    "set_no_show_all",
    "set_opacity",
    "set_parent",
    "set_parent_window",
    "set_realized",
    "set_receives_default",
    "set_redraw_on_allocate",
    "set_sensitive",
    "set_size_request",
    "set_state_flags",
    "set_support_multidevice",
    "set_tooltip_markup",
    "set_tooltip_text",
    "set_tooltip_window",
    "set_valign",
    "set_vexpand",
    "set_vexpand_set",
    "set_visible",
    "set_visual",
    "set_window",
    "shape_combine_region",
    "show",
    "show_all",
    "show_now",
    "size_allocate",
    "size_allocate_with_baseline",
    "size_request",
    "style_get_property",
    "thaw_child_notify",
    "translate_coordinates",
    "trigger_tooltip_query",
    "unmap",
    "unparent",
    "unrealize",
    "unregister_window",
    "unset_state_flags",
]
EXPECTED_WIDGET_PROPERTIES = {
    "app_paintable": False,
    "can_default": False,
    "can_focus": False,
    "composite_child": False,
    "events": Gdk.EventMask.ALL_EVENTS_MASK,
    "expand": False,
    "focus_on_click": True,
    "halign": Gtk.Align.FILL,
    "has_default": False,
    "has_focus": False,
    "has_tooltip": False,
    "height_request": -1,
    "hexpand": False,
    "hexpand_set": False,
    "is_focus": False,
    "margin": 0,
    "margin_bottom": 0,
    "margin_end": 0,
    "margin_start": 0,
    "margin_top": 0,
    "name": "pytkwrap GTK3 widget",
    "no_show_all": False,
    "opacity": 1.0,
    "parent": None,
    "receives_default": False,
    "scale_factor": 1,
    "sensitive": True,
    "style": None,
    "tooltip_markup": "Missing tooltip, please file an issue to have one added.",
    "tooltip_text": "Missing tooltip, please file an issue to have one added.",
    "valign": Gtk.Align.FILL,
    "vexpand": False,
    "vexpand_set": False,
    "visible": False,
    "width_request": -1,
    "window": None,
}
