from _typeshed import Incomplete
from datetime import date
from pytkwrap.gtk3._libs import GObject as GObject, Gtk as Gtk
from pytkwrap.gtk3.combo import ComboBox as ComboBox
from pytkwrap.gtk3.entry import Entry as Entry
from pytkwrap.gtk3.label import Label as Label
from pytkwrap.gtk3.textview import TextView as TextView
from pytkwrap.gtk3.widget import BaseWidget as BaseWidget, WidgetAttributes as WidgetAttributes, WidgetProperties as WidgetProperties

class MatrixView(Gtk.Grid, BaseWidget):
    _MATRIXVIEW_ATTRIBUTES: Incomplete
    _MATRIXVIEW_PROPERTIES: Incomplete
    n_columns: int
    n_rows: int
    def __init__(self) -> None: ...
    def do_get_attribute(self, attribute: str) -> bool | date | float | int | str | None: ...
    def do_set_attributes(self, attributes: WidgetAttributes) -> None: ...
    def do_set_properties(self, properties: WidgetProperties) -> None: ...
    def do_add_column(self, position: int) -> None: ...
    def do_add_label(self, angle: float, heading: str, height: int, position: tuple[int, int], tooltip: str, width: int) -> None: ...
    def do_add_row(self, position: int) -> None: ...
    def do_add_widget(self, widget: ComboBox | Entry | Label | TextView, left: int, top: int, height: int, width: int): ...
    def do_build_matrix(self, column_names: list[tuple[str, str]], row_names: list[tuple[str, str]]) -> None: ...
    def do_get_widget(self, column: int, row: int) -> ComboBox | Entry | Label | TextView | None: ...
    def do_remove_column(self, position: int) -> None: ...
    def do_remove_row(self, position: int) -> None: ...
    def do_set_column_headings(self, column_names: list[tuple[str, str]]) -> None: ...
    def do_set_row_headings(self, row_names: list[tuple[str, str]]) -> None: ...
