from _typeshed import Incomplete
from matplotlib.backend_bases import MouseEvent
from matplotlib.backends.backend_gtk3cairo import FigureCanvasGTK3Cairo as FigureCanvas
from matplotlib.figure import Figure
from pytkwrap.common import PlotWidgetAttributes as PlotWidgetAttributes, PlotWidgetMixin as PlotWidgetMixin
from pytkwrap.gtk3._libs import Gdk as Gdk, Gtk as Gtk, _ as _
from pytkwrap.gtk3.widget import GTK3BaseWidget as GTK3BaseWidget

class GTK3PlotView(GTK3BaseWidget, PlotWidgetMixin):
    _GTK3_PLOTVIEW_ATTRIBUTES: Incomplete
    _max_values: list[float]
    _min_values: list[float]
    figure: Figure
    canvas: FigureCanvas
    axis: Incomplete
    def __init__(self) -> None: ...
    def do_load_plot(self, x_values: list[float], y_values: list[float], marker: str = 'o', plot_type: str = 'scatter') -> None: ...
    def do_add_line(self, x_values: list[float], y_values: list[float] | None = None, color: str = 'k', marker: str = '^') -> None: ...
    def do_close_plot(self, __window: Gtk.Window, /, __event: Gdk.Event, parent: Gtk.Widget) -> None: ...
    def do_expand_plot(self, event: MouseEvent) -> None: ...
    def _do_make_date_plot(self, x_values: list[float], y_values: list[float], marker: str = 'g-') -> None: ...
    def _do_make_histogram(self, x_values: list[float], y_values: list[float], marker: str = 'g') -> None: ...
    def _do_make_scatter_plot(self, x_values: list[float], y_values: list[float], marker: str = 'go') -> None: ...
    def _do_make_step_plot(self, x_values: list[float], y_values: list[float], marker: str = 'g-') -> None: ...
    def _get_minimax_ordinates(self) -> tuple[float, float]: ...
