import matplotlib
from _typeshed import Incomplete
from pytkwrap.gtk3._libs import Gdk as Gdk, Gtk as Gtk, _ as _
from pytkwrap.gtk3.widget import BaseWidget as BaseWidget, WidgetAttributes as WidgetAttributes, WidgetProperties as WidgetProperties

class PlotView(BaseWidget):
    _PLOTVIEW_ATTRIBUTES: Incomplete
    _max_values: list[float]
    _min_values: list[float]
    figure: matplotlib.figure.Figure
    canvas: Incomplete
    axis: Incomplete
    def __init__(self) -> None: ...
    def do_load_plot(self, x_values: list[float], y_values: list[float], marker: str = 'o', plot_type: str = 'scatter') -> None: ...
    def do_add_line(self, x_values: list[float], y_values: list[float] | None = None, color: str = 'k', marker: str = '^') -> None: ...
    def do_close_plot(self, __window: Gtk.Window, /, __event: Gdk.Event, parent: Gtk.Widget) -> None: ...
    def do_expand_plot(self, event: matplotlib.backend_bases.MouseEvent) -> None: ...
    def _do_make_date_plot(self, x_values: list[float], y_values: list[float], marker: str = 'g-') -> None: ...
    def _do_make_histogram(self, x_values: list[float], y_values: list[float], marker: str = 'g') -> None: ...
    def _do_make_scatter_plot(self, x_values: list[float], y_values: list[float], marker: str = 'o') -> None: ...
    def _do_make_step_plot(self, x_values: list[float], y_values: list[float], marker: str = 'g-') -> None: ...
    def _get_minimax_ordinates(self) -> tuple[float, float]: ...
