# Third Party Imports
from _typeshed import Incomplete

class PytkwrapError(Exception):
    msg: Incomplete
    def __init__(self, msg: str = "An error occurred with pytkwrap.") -> None: ...
    def __str__(self) -> str: ...

class NoValueError(PytkwrapError):
    def __init__(self, msg: str = "No value to return.") -> None: ...

class UnkAttributeError(PytkwrapError):
    def __init__(self, msg: str = "Unknown attribute name.") -> None: ...

class UnkPropertyError(PytkwrapError):
    def __init__(self, msg: str = "Unknown property name.") -> None: ...

class UnkSignalError(PytkwrapError):
    def __init__(self, msg: str = "Unknown signal name.") -> None: ...

class WrongTypeError(PytkwrapError):
    def __init__(self, msg: str = "Wrong data type.") -> None: ...
