# Standard Library Imports
import gettext
from collections.abc import Callable as Callable
from dataclasses import dataclass
from datetime import date
from typing import Any

_ = gettext.gettext

@dataclass
class FontDescription:
    allow_breaks: str = ...
    bgalpha: str = ...
    bgcolor: str = ...
    family: str = ...
    features: str = ...
    fgalpha: str = ...
    fgcolor: str = ...
    gravity: str = ...
    gravity_hint: str = ...
    insert_hyphens: str = ...
    lang: str = ...
    letter_spacing: float = ...
    overline: str = ...
    overline_color: str = ...
    rise: str = ...
    scale: str = ...
    size: int = ...
    stretch: str = ...
    strikethrough: str = ...
    strikethrough_color: str = ...
    style: str = ...
    underline: str = ...
    underline_color: str = ...
    variant: str = ...
    weight: str = ...
    def to_string(self) -> str: ...
    def to_markup(self) -> str: ...

def boolean_to_integer(boolean: bool) -> int: ...
def clamp(
    value: float | int, minimum: float | int, maximum: float | int
) -> float | int: ...
def date_to_ordinal(date_string: str) -> int: ...
def deprecated(function: Callable) -> Callable: ...
def dir_exists(directory: str) -> bool: ...
def do_subscribe_to_messages(messages: dict[str, Callable]) -> None: ...
def do_unsubscribe_from_messages(messages: dict[str, Callable]) -> None: ...
def file_exists(_file: str) -> bool: ...
def get_home_directory() -> str: ...
def get_install_prefix() -> str: ...
def integer_to_boolean(integer: int) -> bool: ...
def none_to_default(
    field: bool | date | float | int | str | None,
    default: bool | date | float | int | str | None,
) -> bool | date | float | int | str | None: ...
def none_to_string(string: str | None) -> str: ...
def ordinal_to_date(ordinal: int) -> str: ...
def string_to_date(date_string: str) -> date: ...
def split_string(string: str, delimiter: str = ":") -> list[str]: ...
def sort_dict(
    dictionary: dict[Any, Any], by_value: bool = True, reverse: bool = False
) -> dict[Any, Any]: ...
def string_to_boolean(string: bool | str) -> bool: ...
