# Standard Library Imports
import sys
from datetime import date

try:
    # Third Party Imports
    import gi

    gi.require_version("Gdk", "3.0")
    gi.require_version("GLib", "2.0")
    gi.require_version("Gtk", "3.0")
except ImportError:
    print("Failed to import package gi; exiting.")
    sys.exit(1)
# Third Party Imports
from gi.repository import GObject, Gtk

EXPECTED_CALENDAR_ATTRIBUTES = {
    "default_value": date.today(),
    "edit_signal": [
        "day-selected",
        "month-changed",
        "next-month",
        "next-year",
        "prev-month",
        "prev-year",
    ],
}
EXPECTED_CALENDAR_HANDLER_IDS = {
    "day-selected": -1,
    "day-selected-double-click": -1,
    "month-changed": -1,
    "next-month": -1,
    "next-year": -1,
    "prev-month": -1,
    "prev-year": -1,
}
EXPECTED_CALENDAR_METHODS = [
    "clear_marks",
    "get_date",
    "get_day_is_marked",
    "get_detail_height_rows",
    "get_detail_width_chars",
    "get_display_options",
    "mark_day",
    "select_day",
    "select_month",
    "set_detail_func",
    "set_detail_height_rows",
    "set_detail_width_chars",
    "set_display_options",
    "unmark_day",
]
EXPECTED_CALENDAR_PROPERTIES = {
    "day": 0,
    "detail_height_rows": 0,
    "detail_width_chars": 0,
    "month": 0,
    "no_month_change": False,
    "show_day_names": True,
    "show_details": True,
    "show_heading": True,
    "show_week_numbers": False,
    "year": 0,
}

EXPECTED_COMBOBOX_ATTRIBUTES = {
    "column_types": [GObject.TYPE_STRING],
    "default_value": -1,
    "edit_signal": "changed",
}
EXPECTED_COMBOBOX_HANDLER_IDS = {
    "changed": -1,
    "editing-done": -1,
    "format-entry-text": -1,
    "move-active": -1,
    "popdown": -1,
    "popup": -1,
    "remove-widget": -1,
}
EXPECTED_COMBOBOX_METHODS = [
    "get_active",
    "get_active_id",
    "get_active_iter",
    "get_add_tearoffs",
    "get_button_sensitivity",
    "get_column_span_column",
    "get_entry_text_column",
    "get_has_entry",
    "get_id_column",
    "get_model",
    "get_popup_accessible",
    "get_popup_fixed_width",
    "get_row_span_column",
    "get_wrap_width",
    "popdown",
    "popup",
    "popup_for_device",
    "set_active",
    "set_active_id",
    "set_active_iter",
    "set_button_sensitivity",
    "set_column_span_column",
    "set_entry_text_column",
    "set_id_column",
    "set_model",
    "set_popup_fixed_width",
    "set_row_separator_func",
    "get_row_span_column",
    "set_wrap_width",
]
EXPECTED_COMBOBOX_PROPERTIES = {
    "active": -1,
    "active_id": None,
    "button_sensitivity": Gtk.SensitivityType.AUTO,
    "cell_area": None,
    "column_span_column": -1,
    "editing_canceled": False,
    "entry_text_column": -1,
    "has_entry": False,
    "has_frame": True,
    "id_column": -1,
    "model": None,
    "popup_fixed_width": True,
    "popup_shown": False,
    "row_span_column": -1,
    "wrap_width": 0,
}

EXPECTED_COMBOBOXTEXT_METHODS = [
    "append",
    "append_text",
    "get_active_text",
    "insert",
    "insert_text",
    "prepend",
    "prepend_text",
    "remove",
    "remove_all",
]

SIMPLE_TEST_LIST = [
    "Index 1",
    "Index 2",
    "Index 3",
]
COMPOUND_TEST_LIST = [
    ["This", "is", "a"],
    ["test", "of", "the"],
    ["ComboBox", "not", "simple"],
]

EXPECTED_TEXTVIEW_ATTRIBUTES = {"default_value": "", "edit_signal": "changed"}
EXPECTED_TEXTVIEW_HANDLER_IDS = {
    "backspace": -1,
    "copy-clipboard": -1,
    "cut-clipboard": -1,
    "delete-from-cursor": -1,
    "extend-selection": -1,
    "insert-at-cursor": -1,
    "insert-emoji": -1,
    "move-cursor": -1,
    "move-viewport": -1,
    "paste-clipboard": -1,
    "populate-popup": -1,
    "preedit-changed": -1,
    "select-all": -1,
    "set-anchor": -1,
    "toggle-cursor-visible": -1,
    "toggle-overwrite": -1,
}
EXPECTED_TEXTVIEW_METHODS = [
    "add_child_at_anchor",
    "add_child_in_window",
    "backward_display_line",
    "backward_display_line_start",
    "buffer_to_window_coords",
    "forward_display_line",
    "forward_display_line_end",
    "get_accepts_tab",
    "get_border_window_size",
    "get_bottom_margin",
    "get_buffer",
    "get_cursor_locations",
    "get_cursor_visible",
    "get_default_attributes",
    "get_editable",
    "get_indent",
    "get_input_hints",
    "get_input_purpose",
    "get_iter_at_location",
    "get_iter_at_position",
    "get_iter_location",
    "get_justification",
    "get_left_margin",
    "get_line_at_y",
    "get_line_yrange",
    "get_monospace",
    "get_overwrite",
    "get_pixels_above_lines",
    "get_pixels_below_lines",
    "get_pixels_inside_wrap",
    "get_right_margin",
    "get_tabs",
    "get_top_margin",
    "get_visible_rect",
    "get_window",
    "get_window_type",
    "get_wrap_mode",
    "im_context_filter_keypress",
    "move_child",
    "move_mark_onscreen",
    "move_visually",
    "place_cursor_onscreen",
    "reset_cursor_blink",
    "reset_im_context",
    "scroll_mark_onscreen",
    "scroll_to_iter",
    "scroll_to_mark",
    "set_accepts_tab",
    "set_border_window_size",
    "set_bottom_margin",
    "set_buffer",
    "set_cursor_visible",
    "set_editable",
    "set_indent",
    "set_input_hints",
    "set_input_purpose",
    "set_justification",
    "set_left_margin",
    "set_monospace",
    "set_overwrite",
    "set_pixels_above_lines",
    "set_pixels_below_lines",
    "set_pixels_inside_wrap",
    "set_right_margin",
    "set_tabs",
    "set_top_margin",
    "set_wrap_mode",
    "starts_display_line",
    "window_to_buffer_coords",
]
EXPECTED_TEXTVIEW_PROPERTIES = {
    "accepts_tab": True,
    "bottom_margin": 0,
    "buffer": None,
    "cursor_visible": True,
    "editable": True,
    "im_module": None,
    "indent": 0,
    "input_hints": Gtk.InputHints.NONE,
    "input_purpose": Gtk.InputPurpose.FREE_FORM,
    "justification": Gtk.Justification.LEFT,
    "left_margin": 0,
    "monospace": False,
    "overwrite": False,
    "pixels_above_lines": 0,
    "pixels_below_lines": 0,
    "pixels_inside_wrap": 0,
    "populate_all": False,
    "right_margin": 0,
    "tabs": None,
    "top_margin": 0,
    "wrap_mode": Gtk.WrapMode.NONE,
}
