# Standard Library Imports
from collections.abc import Mapping

# Third Party Imports
from _typeshed import Incomplete

# pytkwrap Package Imports
from pytkwrap.gtk3._libs import GObject as GObject
from pytkwrap.gtk3._libs import Gtk as Gtk
from pytkwrap.gtk3.button.radiobutton import GTK3RadioButton as GTK3RadioButton
from pytkwrap.gtk3.io.label import GTK3Label as GTK3Label
from pytkwrap.gtk3.mixins import GTK3WidgetProperties as GTK3WidgetProperties
from pytkwrap.gtk3.tool.toggletoolbutton import (
    GTK3ToggleToolButtonMixin as GTK3ToggleToolButtonMixin,
)

class GTK3RadioToolButtonMixin(GTK3ToggleToolButtonMixin):
    _GTK3_RADIOTOOLBUTTON_PROPERTIES: Incomplete
    def __init__(self, **kwargs) -> None: ...
    def do_set_properties(
        self, properties: Mapping[str, object] | list[list | tuple]
    ) -> None: ...

class GTK3RadioToolButton(Gtk.ToolItem, GTK3RadioToolButtonMixin):
    _group: Incomplete
    _box: Incomplete
    _radio_button: Incomplete
    _label: Incomplete
    def __init__(self, group: list | None = None) -> None: ...
    def get_active(self) -> bool: ...
    def get_group(self) -> list | None: ...
    def get_icon_name(self) -> None: ...
    def get_icon_widget(self) -> None: ...
    def get_label(self) -> str: ...
    def get_label_widget(self) -> GTK3Label: ...
    def get_use_underline(self) -> bool: ...
    def set_active(self, active: bool) -> None: ...
    def set_group(self, group: list | None = None) -> None: ...
    def set_icon_name(self, icon_name: str) -> None: ...
    def set_icon_widget(self, icon_widget: Gtk.Widget) -> None: ...
    def set_label(self, text: str) -> None: ...
    def set_label_widget(self, label_widget: Gtk.Widget) -> None: ...
    def set_use_underline(self, use_underline: bool) -> None: ...
    def _on_toggled(self, widget: Gtk.ToggleToolButton) -> None: ...
    @classmethod
    def create_group(cls, count: int = 2) -> list[GTK3RadioToolButton]: ...
    @GObject.Signal
    def clicked(self) -> None: ...
    @GObject.Signal
    def toggled(self) -> None: ...
