# Standard Library Imports
import sys

try:
    # Third Party Imports
    import gi

    gi.require_version("Gdk", "3.0")
    gi.require_version("GLib", "2.0")
    gi.require_version("Gtk", "3.0")
except ImportError:
    print("Failed to import package gi; exiting.")
    sys.exit(1)
# Third Party Imports
from gi.repository import Gdk, Gtk

EXPECTED_PAGESETUP_METHODS = [
    "copy",
    "get_bottom_margin",
    "get_left_margin",
    "get_orientation",
    "get_page_height",
    "get_page_width",
    "get_paper_height",
    "get_paper_size",
    "get_paper_width",
    "get_right_margin",
    "get_top_margin",
    "load_file",
    "load_key_file",
    "set_bottom_margin",
    "set_left_margin",
    "set_orientation",
    "set_paper_size",
    "set_paper_size_and_default_margins",
    "set_right_margin",
    "set_top_margin",
    "to_file",
    "to_gvariant",
    "to_key_file",
]

EXPECTED_PRINTCONTEXT_METHODS = [
    "create_pango_context",
    "create_pango_layout",
    "get_cairo_context",
    "get_dpi_x",
    "get_dpi_y",
    "get_hard_margins",
    "get_height",
    "get_page_setup",
    "get_pango_fontmap",
    "get_width",
    "set_cairo_context",
]

EXPECTED_PRINTOPERATION_HANDLER_IDS = {
    "begin-print": -1,
    "create-custom-widget": -1,
    "custom-widget-apply": -1,
    "done": -1,
    "draw-page": -1,
    "end-print": -1,
    "paginate": -1,
    "preview": -1,
    "request-page-setup": -1,
    "status-changed": -1,
    "update-custom-widget": -1,
}
EXPECTED_PRINTOPERATION_METHODS = [
    "cancel",
    "draw_page_finish",
    "get_default_page_setup",
    "get_embed_page_setup",
    "get_error",
    "get_has_selection",
    "get_n_pages_to_print",
    "get_print_settings",
    "get_status",
    "get_status_string",
    "get_support_selection",
    "is_finished",
    "run",
    "set_allow_async",
    "set_current_page",
    "set_custom_tab_label",
    "set_default_page_setup",
    "set_defer_drawing",
    "set_embed_page_setup",
    "set_export_filename",
    "set_has_selection",
    "set_job_name",
    "set_n_pages",
    "set_print_settings",
    "set_show_progress",
    "set_support_selection",
    "set_track_print_status",
    "set_unit",
    "set_use_full_page",
]
EXPECTED_PRINTOPERATION_PROPERTIES = {
    "allow_async": False,
    "current_page": -1,
    "custom_tab_label": None,
    "default_page_setup": None,
    "embed_page_setup": False,
    "export_filename": None,
    "has_selection": False,
    "job_name": "",
    "n_pages": -1,
    "print_settings": None,
    "show_progress": False,
    "support_selection": False,
    "track_print_status": False,
    "unit": Gtk.Unit.NONE,
    "use_full_page": False,
}

EXPECTED_PRINTSETTINGS_METHODS = [
    "copy",
    "foreach",
    "get",
    "get_bool",
    "get_collate",
    "get_default_source",
    "get_dither",
    "get_double",
    "get_double_with_default",
    "get_duplex",
    "get_finishings",
    "get_int",
    "get_int_with_default",
    "get_media_type",
    "get_n_copies",
    "get_number_up",
    "get_orientation",
    "get_output_bin",
    "get_page_ranges",
    "get_page_set",
    "get_paper_height",
    "get_paper_size",
    "get_paper_width",
    "get_print_pages",
    "get_printer",
    "get_printer_lpi",
    "get_resolution_x",
    "get_resolution_y",
    "get_reverse",
    "get_scale",
    "get_use_color",
    "has_key",
    "load_file",
    "load_key_file",
    "set",
    "set_bool",
    "set_collate",
    "set_default_source",
    "set_dither",
    "set_double",
    "set_duplex",
    "set_finishings",
    "set_int",
    "set_length",
    "set_media_type",
    "set_n_copies",
    "set_number_up",
    "set_number_up_layout",
    "set_orientation",
    "set_output_bin",
    "set_page_ranges",
    "set_page_set",
    "set_paper_size",
    "set_paper_width",
    "set_print_pages",
    "set_printer",
    "set_printer_lpi",
    "set_quality",
    "set_resolution",
    "set_resolution_xy",
    "set_reverse",
    "set_scale",
    "set_use_color",
    "to_file",
    "to_gvariant",
    "to_key_file",
    "unset",
]
